### ISSUE TITLE
Add eeprom config over Serial Monitor

### ISSUE THREAD

**Issue by silverailscolo** [silverailscolo/Arduino-GCA51#5]
Using a simple Arduino lib (2013) [ArduinoSerialCommand](https://github.com/scogswell/ArduinoSerialCommand)
After testing I selected a more recent fork: SerialCommand_Advanced by [argandas](https://github.com/argandas/SerialCommand)

**Comment by silverailscolo** [comment]
New .yml action:
```
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
```
